version: "3"

tasks:

  generate-grpc-api:
    desc: Generate golang code from proto files
    dotenv: ['.env']
    aliases:
      - gen
    cmd: sh $SCRIPTS_DIR/generate.sh $GOLANG_GEN_DIR $PROTOS_DIR
