basePath: /
definitions:
  authentication.Account:
    properties:
      id:
        type: string
    type: object
  authentication.HTTPError:
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: sso
  version: 0.0.1
paths:
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authentication.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/authentication.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/authentication.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/authentication.HTTPError'
      summary: Show an account
      tags:
      - accounts
  /api/ping:
    get:
      produces:
      - text/html
      responses:
        "200":
          description: ok
          schema:
            type: string
        "406":
          description: not ok
          schema:
            type: string
      summary: Регистрация пользователя
      tags:
      - system
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
